# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='owner',
        ),
    ]
