# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_bucketlist_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucketlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
